#!/usr/bin/zsh

_cmount() {
    sudo mount -t cifs "$1" "$2" -o _netdev,credentials="$3"
}

_credfile() {
    pass show Work | sed 's/: /=/; 1s/^/password=/'
}

cmount() {
    mkdir -p "${HOME}/c5shares/$1"
    _cmount "//$1/c$" "${HOME}/c5shares/$1" =(_credfile)
    cd "${HOME}/c5shares/$1"
}

cfiles() {
    _cmount "//circuit5.org/files" "${HOME}/c5shares/files" =(_credfile)
    cd "${HOME}/c5shares/files"
}

findmount() {
    machines="$(cmachine "$1")"
    for machine in $machines ; do
	mkdir -p "${HOME}/c5shares/$machine"
	echo "Mounting ${machine}'s C:\\"
	_cmount "//${machine}/c$" "${HOME}/c5shares/${machine}" =(_credfile)
	cd "${HOME}/c5shares/${machine}"
	ls
    done
}
