David's Guide to Appeasement of Finance

* When you receive your receipt for any purchases you've made
  1) Scan, sign, file in pending receipts.
  2) Log in to Works: https://payment2.works.com/works/home
  3) If the transaction isn't there:
     1) Set a reminder to check back in a few days.
     Else:
     1) Click on "No" under "Uploaded Receipt".
     2) Add -> New Receipt
     3) Pick your file, the date.
     4) Put in a description of the items.
     5) OK. You've uploaded a receipt. Now you need to tell them you have the receipt, because even if you upload it, that doesn't mean it actually exists.
     6) Close the receipt window and open the other receipt window. How do you do that? Click on the Receipts button on the bottom. This is separate from the receipt window you get while uploading the receipts, see?
     7) Say, yes, I have the receipt. I just sent it to you. Why do I need to repeat myself?
     8) While you're repeating yourself, there's another comment/description line here. This is called the Receipt Comment. The comment you put in while uploading the receipt is NOT the Receipt Comment. Make sense? No? Good. No good ritual is complete without some mystery.
     9) Put the receipt comment in ALL CAPS, because the finance department is down the street and we have to yell for them to hear us. DO NOT yell for the first description in step 3.4; that would be rude.
     10) Make sure the ORG and OBJECT codes are right. These should be in the original purchase ticket, or you can get them from the budget spreadsheets. It's not always clear where the delineations are between these, so try to get someone else to pick them for you. They'll usually be 6062300 and 830511, though.
     11) Double check that the ritual has been performed correctly.
     12) When you are sure you're safe to proceed, click the transaction number in the Document column and select Sign Off. DO NOT click Sign Off until you are sure; the submission will be made and you have no chance to make changes thereafter. Here's another comment field. This one is unnecessary, but if you want to put another description of your purchase here, it can't hurt.
  4) Print a copy of the signed receipt, and put them in a folder to send when your statement is ready. All the steps above are to appease the machine. However, the receipt isn't real until the finance department can lick it or whatever they do, so you have to send dead trees as sacrifice. DO NOT suggest that they can produce these copies themselves; your sweat must make contact with the page for alchemical reasons.

* When you receive the email from Works saying your statement's ready
  If the above steps have been completed for all transactions:
    1) Download the PDF created and add your signature, storing it with the others to prevent contamination of your filesystem.
    2) Email the signed statement to Kasey Merlington and Linda Lorentz. The Machine provides no means; you are on your own, pilgrim.
    3) Print out a copy, add it to the folder referred to in step 4 above, and send the folder to finance through inter-office mail
  Else:
    1) Follow the "receipt received" steps above for all transactions
    2) In Works, go to Reports -> Scheduled
    3) Click on the report name, then Modify/Run
    4) Scroll to the Scheduling and Expiration section at the bottom
    5) Change the radio from its recurring schedule to "Run Now"
    6) This deselects the recurring schedule. You may think that your scheduled task is being removed; this is a lie told you by the machine to test your faith.
    7) Press forward in that faith, selecting the "Submit Report" button
    8) Reflect on your sins/supplicate before the machine as you wait for its decision to grant your puny request
    9) Follow the above "steps have been completed" section of this process
